from ..models import *

####### CATEGORIAS #######
Categoria.objects.create(nome="Indefinido(a)", categoria_pai = None)
Categoria.objects.create(nome="Alimentos", categoria_pai = None)
Categoria.objects.create(nome="Frutas e Legumes", categoria_pai=2)
Categoria.objects.create(nome="Frutas", categoria_pai=3)
Categoria.objects.create(nome="Legumes", categoria_pai=3)
Categoria.objects.create(nome="Lacticínios", categoria_pai=2)
Categoria.objects.create(nome="Leite", categoria_pai=6)
Categoria.objects.create(nome="Queijos", categoria_pai=6)
Categoria.objects.create(nome="Iogurtes", categoria_pai=6)
Categoria.objects.create(nome="Doces e Sobremesas", categoria_pai=2)
Categoria.objects.create(nome="Doces", categoria_pai=10)
Categoria.objects.create(nome="Sobremesas", categoria_pai=10)
Categoria.objects.create(nome="Chocolates", categoria_pai=11)
Categoria.objects.create(nome="Gomas", categoria_pai=11)
Categoria.objects.create(nome="Mercearia", categoria_pai=2)
Categoria.objects.create(nome="Conservas", categoria_pai=15)
Categoria.objects.create(nome="Arroz, Massa e Farinha", categoria_pai=15)
Categoria.objects.create(nome="Arroz", categoria_pai=17)
Categoria.objects.create(nome="Massa", categoria_pai=17)
Categoria.objects.create(nome="Farinha", categoria_pai=17)
Categoria.objects.create(nome="Atum", categoria_pai=16)
Categoria.objects.create(nome="Conservas de Peixe", categoria_pai=16)
Categoria.objects.create(nome="Salsichas e Cogumelos", categoria_pai=16)
Categoria.objects.create(nome="Salsichas", categoria_pai=23)
Categoria.objects.create(nome="Cogumelos", categoria_pai=23)
Categoria.objects.create(nome="Patê", categoria_pai=16)
Categoria.objects.create(nome="Feijão, Grão e Milho", categoria_pai=16)
Categoria.objects.create(nome="Feijão", categoria_pai=27)
Categoria.objects.create(nome="Grão", categoria_pai=27)
Categoria.objects.create(nome="Milho", categoria_pai=27)
Categoria.objects.create(nome="Congelados", categoria_pai=2)
Categoria.objects.create(nome="Ervilhas e outros legumes", categoria_pai=31)
Categoria.objects.create(nome="Gelados", categoria_pai=12)
Categoria.objects.create(nome="Sobremesas Tradicionais", categoria_pai=12)
Categoria.objects.create(nome="Doces Conventuais", categoria_pai=11)
Categoria.objects.create(nome="Cereais e Barras", categoria_pai=15)
Categoria.objects.create(nome="Cereais", categoria_pai=36)
Categoria.objects.create(nome="Barras", categoria_pai=36)
Categoria.objects.create(nome="Azeite, Óleo e Vinagre", categoria_pai=15)
Categoria.objects.create(nome="Azeite", categoria_pai=39)
Categoria.objects.create(nome="Óleo", categoria_pai=39)
Categoria.objects.create(nome="Vinagre", categoria_pai=39)
Categoria.objects.create(nome="Café, Chá e Acholatado em Pó", categoria_pai=15)
Categoria.objects.create(nome="Snacks e Batata Frita", categoria_pai=15)
Categoria.objects.create(nome="Snacks", categoria_pai=44)
Categoria.objects.create(nome="Batata Frita", categoria_pai=44)
Categoria.objects.create(nome="Molhos e Condimentos", categoria_pai=15)
Categoria.objects.create(nome="Molhos", categoria_pai=47)
Categoria.objects.create(nome="Condimentos", categoria_pai=47)
Categoria.objects.create(nome="Manteiga e Cremes para barrar", categoria_pai=6)
Categoria.objects.create(nome="Manteiga", categoria_pai=50)
Categoria.objects.create(nome="Cremes para Barrar", categoria_pai=50)
Categoria.objects.create(nome="Pizzas Congeladas", categoria_pai=31)
Categoria.objects.create(nome="Douradinhos e Nuggets", categoria_pai=31)
Categoria.objects.create(nome="Douradinhos", categoria_pai=54)
Categoria.objects.create(nome="Nuggets", categoria_pai=54)
Categoria.objects.create(nome="Padaria e Pastelaria", categoria_pai=2)
Categoria.objects.create(nome="Padaria", categoria_pai=57)
Categoria.objects.create(nome="Pastelaria", categoria_pai=57)
Categoria.objects.create(nome="Pão", categoria_pai=57)
####### FIM CATEGORIAS #######