# Generated by Django 4.1.7 on 2023-05-13 00:47

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import loja.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um utilizador com esse e-mail.'}, max_length=254, null=True, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'Já existe um utilizador com esse nome de utilizador.'}, help_text='Máximo 20 caracteres. Apenas letras, números e os seguintes símbolos @/./+/-/_ ', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()])),
                ('pais', django_countries.fields.CountryField(default='PT', max_length=2, null=True)),
                ('cidade', models.CharField(max_length=200, null=True)),
                ('telemovel', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'Já existe um utilizador com esse número de telefone.'}, help_text='O País default para os números de telemóvel é Portugal(+351). Se o seu número for de um país diferente tem de adicionar o identificador desse país.', max_length=128, null=True, region=None, unique=True)),
                ('tipo_utilizador', models.CharField(choices=[('C', 'CONSUMIDOR'), ('F', 'FORNECEDOR')], default='', max_length=1, null=True)),
                ('imagem_perfil', models.ImageField(default='avatar.svg', null=True, upload_to='', validators=[loja.models.Utilizador.validar_extensao_imagens, loja.models.Utilizador.validar_tamanho_imagens])),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se este utilizador pode aceder à área de administração do site.')),
                ('is_admin', models.BooleanField(default=False, help_text='Designa se este utilizador tem permissão para realizar ações de administrador.')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'ordering': ['id', 'username', 'telemovel', '-created', '-updated'],
            },
            managers=[
                ('objects', loja.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True)),
                ('is_variante', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
            },
        ),
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='loja.consumidor')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categoria', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='UnidadeProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('pais', django_countries.fields.CountryField(default='PT', max_length=2, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('morada', models.CharField(max_length=200, null=True)),
                ('tipo_unidade', models.CharField(choices=[('A', 'Armazém'), ('Q', 'Quinta'), ('MM', 'Mini-mercado'), ('SM', 'Supermercado'), ('HM', 'Hipermercado'), ('LR', 'Loja de Rua'), ('LCC', 'Loja Centro Comercial'), ('O', 'Outro')], default='', max_length=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_producao', to='loja.fornecedor')),
            ],
            options={
                'verbose_name': 'Unidade de Producao',
                'verbose_name_plural': 'Unidades de Producao',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('tipo_veiculo', models.CharField(choices=[('C', 'Carro'), ('E', 'Estafeta a pé'), ('M', 'Mota'), ('B', 'Bicicleta'), ('T', 'Trotineta'), ('CR', 'Carrinha'), ('CM', 'Camião')], default='', max_length=5, null=True)),
                ('estado_veiculo', models.CharField(choices=[('D', 'Disponível'), ('A-C', 'A caminho'), ('E', 'A entregar'), ('I/M', 'Indisponível/Manutenção'), ('R', 'Regresso'), ('W', 'À espera')], default='D', max_length=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('unidadeProducao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='loja.unidadeproducao')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoUnidadeProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=2)),
                ('data_producao', models.DateField(default=django.utils.timezone.now, null=True)),
                ('preco_por_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantidade_por_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_producao', to='loja.produto')),
                ('unidade_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.unidadeproducao')),
            ],
            options={
                'verbose_name': 'Produto por Unidade Producao',
                'verbose_name_plural': 'Produtos por Unidade Producao',
            },
        ),
        migrations.CreateModel(
            name='ProdutosEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.encomenda')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encomendado', to='loja.produtounidadeproducao')),
            ],
            options={
                'verbose_name': 'Produtos Encomendados',
                'verbose_name_plural': 'Produtos Encomendados',
            },
        ),
        migrations.CreateModel(
            name='ProdutosCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=6, null=True)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='loja.carrinho')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtounidadeproducao')),
            ],
            options={
                'verbose_name': 'Produtos num Carrinho',
                'verbose_name_plural': 'Produtos num Carrinho',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/imagens/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_produto', to='loja.produtounidadeproducao')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.atributo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.categoria')),
            ],
            options={
                'verbose_name': 'Categoria Atributo',
                'verbose_name_plural': 'Categoria Atributos',
            },
        ),
        migrations.AddField(
            model_name='carrinho',
            name='consumidor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='loja.consumidor'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.categoria'),
        ),
    ]
