# Generated by Django 4.1.7 on 2023-06-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['-id'], 'verbose_name': 'Encomenda', 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AlterModelOptions(
            name='produtosencomenda',
            options={'ordering': ['-id'], 'verbose_name': 'Produtos Encomendados', 'verbose_name_plural': 'Produtos Encomendados'},
        ),
    ]
