# Generated by Django 4.1.7 on 2023-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='teste',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='minha_morada',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
