# Generated by Django 4.2.1 on 2023-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosencomenda',
            name='estado',
            field=models.CharField(choices=[('Em processamento', 'Em processamento'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Em processamento', max_length=20),
        ),
    ]
