# Generated by Django 4.1.7 on 2023-05-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_producao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_por_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_por_unidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=2),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/imagens/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_produto', to='loja.produto')),
            ],
        ),
    ]
