# Generated by Django 4.1.7 on 2023-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
