# Generated by Django 4.1.7 on 2023-03-20 01:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'ordering': ['username', '-created', '-updated']},
        ),
        migrations.AddField(
            model_name='utilizador',
            name='cidade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='imagem_perfil',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='morada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='pais',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='telemovel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='tipo_utilizador',
            field=models.CharField(choices=[('C', 'CONSUMIDOR'), ('F', 'FORNECEDOR')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
