# Generated by Django 4.1.7 on 2023-05-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='unidadeProducao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='loja.unidadeproducao'),
        ),
    ]
