# Generated by Django 4.1.7 on 2023-05-26 22:46

from django.db import migrations, models
import loja.models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_categoria_categoria_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtounidadeproducao',
            name='imagem_produto',
            field=models.ImageField(null=True, upload_to='products/', validators=[loja.models.ProdutoUnidadeProducao.validar_extensao_imagens, loja.models.ProdutoUnidadeProducao.validar_tamanho_imagens]),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='imagem_perfil',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='imagens_perfil/', validators=[loja.models.Utilizador.validar_extensao_imagens, loja.models.Utilizador.validar_tamanho_imagens]),
        ),
    ]
