# Generated by Django 4.1.7 on 2023-05-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_veiculo_unidadeproducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='loja.consumidor')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosNoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='loja.carrinho')),
            ],
        ),
    ]
