# Generated by Django 4.1.7 on 2023-05-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_utilizador_morada_remove_utilizador_teste_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilizador',
            old_name='minha_morada',
            new_name='morada',
        ),
    ]
