# Generated by Django 4.2.1 on 2023-06-01 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_encomenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='detalhes_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='loja.detalhesenvio'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
