# Generated by Django 4.1.7 on 2023-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_produto_data_producao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_producao',
            field=models.DateField(null=True),
        ),
    ]
