# Generated by Django 4.1.7 on 2023-06-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produtosencomenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='freguesia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
