# Generated by Django 4.1.7 on 2023-05-12 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.categoria'),
        ),
    ]
