# Generated by Django 4.1.7 on 2023-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produtounidadeproducao_preco_a_granel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtounidadeproducao',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
    ]
