# Generated by Django 4.1.7 on 2023-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_minha_morada_utilizador_morada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhesenvio',
            name='guardar_esta_morada',
            field=models.BooleanField(default=False, help_text='Deseja guardar esta morada para futuras encomendas?'),
        ),
    ]
