# Generated by Django 4.1.7 on 2023-04-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_consumidor_options_alter_utilizador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='morada',
        ),
    ]
