# Generated by Django 4.1.7 on 2023-04-02 02:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_utilizador_options_alter_utilizador_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='username_l',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um utilizador com esse nome de utilizador.'}, help_text='Obrigatório. 20 caracteres ou menos. Apenas letras, dígitos e @/./+/-/_ são permitidos.', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
    ]
