# Generated by Django 4.1.7 on 2023-05-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_carrinho_produtosnocarrinho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutosNoCarrinho',
            new_name='ProdutosCarrinho',
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='produtoscarrinho',
            options={'verbose_name': 'Produtos num Carrinho'},
        ),
    ]
