# Generated by Django 4.1.7 on 2023-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_utilizador_freguesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeproducao',
            name='freguesia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
