# Generated by Django 4.1.7 on 2023-05-11 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_data_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_producao',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 21, 53, 5, 864469, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
