# Generated by Django 4.1.7 on 2023-05-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produtounidadeproducao_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtounidadeproducao',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
