# Generated by Django 4.1.7 on 2023-05-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_produtosnocarrinho_produtoscarrinho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtoscarrinho',
            options={'verbose_name': 'Produtos num Carrinho', 'verbose_name_plural': 'Produtos num Carrinho'},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='descricao',
        ),
    ]
