# Generated by Django 4.1.7 on 2023-05-11 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_data_producao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_producao',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
