# Generated by Django 4.1.7 on 2023-04-02 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_remove_utilizador_username_l_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumidor',
            options={'verbose_name': 'Consumidor', 'verbose_name_plural': 'Consumidores'},
        ),
    ]
