# Generated by Django 4.1.7 on 2023-06-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_unidadeproducao_freguesia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='estado',
            field=models.CharField(choices=[('Em processamento', 'Em processamento'), ('Enviado', 'Enviado'), ('A chegar', 'A chegar'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Em processamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtosencomenda',
            name='estado',
            field=models.CharField(choices=[('Em processamento', 'Em processamento'), ('Enviado', 'Enviado'), ('A chegar', 'A chegar'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Em processamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='produtounidadeproducao',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], help_text='Unidade de medida de venda e do stock', max_length=2),
        ),
        migrations.CreateModel(
            name='ProdutosEncomendadosVeiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('produto_Encomenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja.produtosencomenda')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_no_veiculo', to='loja.veiculo')),
            ],
            options={
                'verbose_name': 'Produto Associado a Veículo',
                'verbose_name_plural': 'Produtos Associados a Veículos',
                'ordering': ['id'],
            },
        ),
    ]
