# Generated by Django 4.1.7 on 2023-05-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_categoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoscarrinho',
            name='produtos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.produtounidadeproducao'),
        ),
    ]
