# Generated by Django 4.1.7 on 2023-06-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produtosencomenda_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosencomenda',
            name='estado',
            field=models.CharField(choices=[('Em processamento', 'Em processamento'), ('A sair da Unidade de Producao', 'A sair da Unidade de Producao'), ('Enviado', 'Enviado'), ('A chegar', 'A chegar'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Em processamento', max_length=30),
        ),
    ]
