# Generated by Django 4.1.7 on 2023-05-11 22:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_produto_data_producao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_producao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_por_unidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_por_unidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade_producao',
        ),
        migrations.CreateModel(
            name='ProdutoUnidadeProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('un', 'Unidade')], max_length=2)),
                ('data_producao', models.DateField(default=django.utils.timezone.now, null=True)),
                ('preco_por_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantidade_por_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('marca', models.CharField(max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_producao', to='loja.produto')),
                ('unidade_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
