# Generated by Django 4.1.7 on 2023-06-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_categoria_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtosencomendadosveiculos',
            old_name='produto_Encomenda',
            new_name='produto_Encomendado',
        ),
    ]
