# Generated by Django 4.1.7 on 2023-05-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produtoscarrinho_produtos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtoscarrinho',
            old_name='produtos',
            new_name='produto',
        ),
    ]
