# Generated by Django 4.1.7 on 2023-05-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_produtounidadeproducao_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoscarrinho',
            name='carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_carrinho', to='loja.carrinho'),
        ),
    ]
