# Generated by Django 4.1.7 on 2023-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_produtos_produtoscarrinho_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoscarrinho',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, null=True),
        ),
    ]
