# Generated by Django 4.1.7 on 2023-05-11 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtounidadeproducao',
            name='categoria',
            field=models.ForeignKey(default=54, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.categoria'),
        ),
    ]
