# Generated by Django 4.1.7 on 2023-05-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_produtoscarrinho_carrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo',
            options={'ordering': ['id'], 'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterModelOptions(
            name='carrinho',
            options={'ordering': ['id'], 'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='categoriaatributo',
            options={'ordering': ['id'], 'verbose_name': 'Categoria Atributo', 'verbose_name_plural': 'Categoria Atributos'},
        ),
        migrations.AlterModelOptions(
            name='consumidor',
            options={'ordering': ['id', 'utilizador'], 'verbose_name': 'Consumidor', 'verbose_name_plural': 'Consumidores'},
        ),
        migrations.AlterModelOptions(
            name='encomenda',
            options={'ordering': ['id'], 'verbose_name': 'Encomenda', 'verbose_name_plural': 'Encomendas'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['id', 'utilizador'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('id', 'nome'), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='produtoscarrinho',
            options={'ordering': ['id'], 'verbose_name': 'Produtos num Carrinho', 'verbose_name_plural': 'Produtos num Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='produtosencomenda',
            options={'ordering': ['id'], 'verbose_name': 'Produtos Encomendados', 'verbose_name_plural': 'Produtos Encomendados'},
        ),
        migrations.AlterModelOptions(
            name='produtounidadeproducao',
            options={'ordering': ['id', 'produto', 'unidade_producao'], 'verbose_name': 'Produto por Unidade Producao', 'verbose_name_plural': 'Produtos por Unidade Producao'},
        ),
        migrations.AlterModelOptions(
            name='unidadeproducao',
            options={'ordering': ['id', 'nome', 'fornecedor'], 'verbose_name': 'Unidade de Producao', 'verbose_name_plural': 'Unidades de Producao'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['id', 'unidadeProducao', 'nome', 'tipo_veiculo', 'estado_veiculo', '-created', '-updated'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
