# Generated by Django 5.0 on 2023-04-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_categoria_marca_produto_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
