# Generated by Django 4.1.7 on 2023-05-14 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_atributo_options_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtounidadeproducao',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
