# Generated by Django 4.1.7 on 2023-05-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_produtounidadeproducao_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaatributo',
            options={'verbose_name': 'Categoria Atributo', 'verbose_name_plural': 'Categoria Atributos'},
        ),
        migrations.AlterModelOptions(
            name='produtounidadeproducao',
            options={'verbose_name': 'Produto por Unidade Producao', 'verbose_name_plural': 'Produtos por Unidade Producao'},
        ),
    ]
