# Generated by Django 4.1.7 on 2023-05-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_produtoscarrinho_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='loja.consumidor')),
            ],
            options={
                'verbose_name': 'Encomenda',
                'verbose_name_plural': 'Encomendas',
            },
        ),
        migrations.CreateModel(
            name='ProdutosEncomendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.encomenda')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encomendado', to='loja.produtounidadeproducao')),
            ],
            options={
                'verbose_name': 'Produtos Encomendados',
                'verbose_name_plural': 'Produtos Encomendados',
            },
        ),
    ]
