# Generated by Django 4.1.7 on 2023-05-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_categoriaatributo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtounidadeproducao',
            name='unidade_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.unidadeproducao'),
        ),
    ]
