# Generated by Django 4.1.7 on 2023-05-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_encomenda_produtosencomendas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutosEncomendas',
            new_name='ProdutosEncomenda',
        ),
    ]
