# Generated by Django 4.1.7 on 2023-05-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_produtounidadeproducao_unidade_producao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtounidadeproducao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(default=54, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.categoria'),
        ),
    ]
