<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-05-18 14:17
=======
# Generated by Django 4.1.7 on 2023-05-16 18:17
>>>>>>> auth0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('loja', '0009_produto_slug'),
=======
        ("loja", "0009_produto_slug"),
>>>>>>> auth0
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='unidadeproducao',
            options={'ordering': ['nome'], 'verbose_name': 'UnidadeProducao', 'verbose_name_plural': 'UnidadesProducao'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['nome'], 'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
=======
            name="unidadeproducao",
            options={
                "ordering": ["nome"],
                "verbose_name": "UnidadeProducao",
                "verbose_name_plural": "UnidadesProducao",
            },
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={
                "ordering": ["nome"],
                "verbose_name": "Veiculo",
                "verbose_name_plural": "Veiculos",
            },
>>>>>>> auth0
        ),
    ]
