# Generated by Django 4.1.7 on 2023-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_produto_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadeproducao',
            options={'ordering': ['nome'], 'verbose_name': 'UnidadeProducao', 'verbose_name_plural': 'UnidadesProducao'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['nome'], 'verbose_name': 'Veiculo', 'verbose_name_plural': 'Veiculos'},
        ),
    ]
