# Generated by Django 4.1.7 on 2023-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_unidadeproducao_options_alter_veiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoscarrinho',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtoscarrinho',
            name='precoKilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
