# Generated by Django 4.1.7 on 2023-05-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_produto', to='loja.produtounidadeproducao'),
        ),
    ]
